GET http://localhost:5000/api
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlkIjoiNzJjN2ZhMWEtY2M0YS00YzRiLTgzOTYtNjRhYTExZWRkZDFlIiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsInBhc3N3b3JkIjoicGFzc0AxMjM0IiwidGVhbXMiOltdLCJpYXQiOjE2MzMyNTI0MTYsImV4cCI6MTYzMzI1MjQ2MX0.6oOJIWs_0RbVdgFWvdOJeTGOZqDBNR8ZRngQvWYAXyc

###

POST http://localhost:5000/auth/loginWithEmailAndPassword
Content-Type: application/json

{
  "name": "test",
  "email": "test1@test.com",
  "password": "pass@1234"
}

###

POST http://localhost:5000/auth/accessToken
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlkIjoiNzJjN2ZhMWEtY2M0YS00YzRiLTgzOTYtNjRhYTExZWRkZDFlIiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsInBhc3N3b3JkIjoicGFzc0AxMjM0IiwidGVhbXMiOltdLCJpYXQiOjE2MzMyNTAyMjh9.yrVNTRAbN3ng9S_6-G3x66BzkqiGTcB0OJq7ymikSWc"
}

###

DELETE http://localhost:5000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlkIjoiNzJjN2ZhMWEtY2M0YS00YzRiLTgzOTYtNjRhYTExZWRkZDFlIiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsInBhc3N3b3JkIjoicGFzc0AxMjM0IiwidGVhbXMiOltdLCJpYXQiOjE2MzMyNTAyMjh9.yrVNTRAbN3ng9S_6-G3x66BzkqiGTcB0OJq7ymikSWc"
}